# Generated by Django 4.2.4 on 2023-08-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='facebook',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='footer',
            name='insta',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='footer',
            name='linkedin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='footer',
            name='twiter',
            field=models.CharField(max_length=50),
        ),
    ]
